// app/src/lib/QuickMove.svelte
<script lang="ts">
  import * as api from './api';
  import type { SearchResult } from './api';
  import { outline } from './outline.svelte';

  interface Props {
    isOpen: boolean;
    onClose: () => void;
  }

  let { isOpen, onClose }: Props = $props();

  let query = $state('');
  let results = $state<SearchResult[]>([]);
  let selectedIndex = $state(0);
  let loading = $state(false);
  let moving = $state(false);
  let inputElement: HTMLInputElement | undefined = $state();

  // The node we're moving
  $effect(() => {
    if (isOpen) {
      query = '';
      results = [];
      selectedIndex = 0;
      setTimeout(() => inputElement?.focus(), 50);
    }
  });

  // Search when query changes
  let searchTimeout: ReturnType<typeof setTimeout> | undefined;

  $effect(() => {
    if (query.trim().length > 0) {
      clearTimeout(searchTimeout);
      searchTimeout = setTimeout(async () => {
        loading = true;
        try {
          results = await api.search(query, undefined, 30);
          selectedIndex = 0;
        } finally {
          loading = false;
        }
      }, 150);
    } else {
      results = [];
      selectedIndex = 0;
    }
  });

  function handleKeydown(event: KeyboardEvent) {
    if (!isOpen) return;

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        selectedIndex = Math.min(selectedIndex + 1, results.length - 1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        selectedIndex = Math.max(selectedIndex - 1, 0);
        break;
      case 'Enter':
        event.preventDefault();
        selectCurrent();
        break;
      case 'Escape':
        event.preventDefault();
        handleClose();
        break;
    }
  }

  async function selectCurrent() {
    const result = results[selectedIndex];
    if (result) {
      await moveToNode(result.node_id);
    }
  }

  async function moveToNode(targetNodeId: string) {
    const sourceId = outline.focusedId;
    if (!sourceId || sourceId === targetNodeId) {
      handleClose();
      return;
    }

    moving = true;
    try {
      // Move the focused node to be a child of the target node
      // Position it at the end of the target's children
      const targetChildren = outline.nodes.filter(n => n.parent_id === targetNodeId);
      const newPosition = targetChildren.length;

      await outline.moveNodeTo(sourceId, targetNodeId, newPosition);

      handleClose();
    } catch (e) {
      console.error('Failed to move node:', e);
    } finally {
      moving = false;
    }
  }

  function selectItem(result: SearchResult) {
    moveToNode(result.node_id);
  }

  function handleClose() {
    query = '';
    results = [];
    selectedIndex = 0;
    onClose();
  }

  function handleBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      handleClose();
    }
  }

  // Scroll selected result into view
  $effect(() => {
    if (results.length > 0) {
      const element = document.querySelector(`[data-move-index="${selectedIndex}"]`);
      element?.scrollIntoView({ block: 'nearest' });
    }
  });

  function getSourceNodeContent(): string {
    const sourceId = outline.focusedId;
    if (!sourceId) return '';
    const node = outline.getNode(sourceId);
    if (!node) return '';
    // Strip HTML tags for display
    const div = document.createElement('div');
    div.innerHTML = node.content;
    const text = div.textContent || div.innerText || '';
    return text.length > 40 ? text.substring(0, 40) + '...' : text;
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if isOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal-backdrop" onclick={handleBackdropClick}>
    <div class="modal">
      <div class="header-info">
        <span class="move-label">Move:</span>
        <span class="source-node">{getSourceNodeContent()}</span>
      </div>

      <div class="search-input-wrapper">
        <svg class="mode-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M5 9l7 7 7-7" />
        </svg>
        <input
          bind:this={inputElement}
          type="text"
          class="search-input"
          placeholder="Move to..."
          bind:value={query}
          disabled={moving}
        />
        {#if loading}
          <span class="loading-indicator">...</span>
        {/if}
        {#if moving}
          <span class="loading-indicator">Moving...</span>
        {/if}
      </div>

      <div class="results">
        {#if results.length === 0 && query.trim().length > 0 && !loading}
          <div class="no-results">No items found</div>
        {:else if results.length === 0 && query.trim().length === 0}
          <div class="hint-text">Search for a destination node...</div>
        {:else}
          {#each results as result, index}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div
              class="result"
              class:selected={index === selectedIndex}
              data-move-index={index}
              onclick={() => selectItem(result)}
            >
              <div class="result-content">
                {@html result.snippet}
              </div>
            </div>
          {/each}
        {/if}
      </div>

      <div class="modal-footer">
        <span class="hint">
          <kbd>↑↓</kbd> Navigate
          <kbd>Enter</kbd> Move here
          <kbd>Esc</kbd> Cancel
        </span>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: flex-start;
    justify-content: center;
    padding-top: 100px;
    z-index: 1000;
  }

  .modal {
    background: var(--bg-elevated);
    border-radius: 12px;
    box-shadow: 0 25px 50px -12px var(--modal-overlay);
    width: 500px;
    max-width: 90vw;
    max-height: 60vh;
    display: flex;
    flex-direction: column;
  }

  .header-info {
    padding: 12px 16px;
    background: var(--accent-primary-lighter);
    border-bottom: 1px solid var(--border-primary);
    border-radius: 12px 12px 0 0;
    font-size: 13px;
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .move-label {
    color: var(--text-secondary);
    font-weight: 500;
  }

  .source-node {
    color: var(--accent-primary);
    font-weight: 500;
  }

  .search-input-wrapper {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 16px;
    border-bottom: 1px solid var(--border-primary);
  }

  .mode-icon {
    width: 20px;
    height: 20px;
    color: var(--text-secondary);
    flex-shrink: 0;
  }

  .search-input {
    flex: 1;
    border: none;
    outline: none;
    font-size: 16px;
    background: transparent;
    color: var(--text-primary);
  }

  .search-input::placeholder {
    color: var(--text-tertiary);
  }

  .search-input:disabled {
    opacity: 0.6;
  }

  .loading-indicator {
    color: var(--text-secondary);
    font-size: 14px;
  }

  .results {
    flex: 1;
    overflow-y: auto;
    max-height: 350px;
  }

  .no-results, .hint-text {
    padding: 24px;
    text-align: center;
    color: var(--text-secondary);
  }

  .result {
    padding: 12px 16px;
    cursor: pointer;
    border-bottom: 1px solid var(--border-secondary);
  }

  .result:last-child {
    border-bottom: none;
  }

  .result:hover,
  .result.selected {
    background: var(--bg-tertiary);
  }

  .result.selected {
    background: var(--selection-bg-strong);
  }

  .result-content {
    font-size: 14px;
    line-height: 1.5;
    color: var(--text-primary);
  }

  .result-content :global(mark) {
    background: var(--highlight-bg);
    color: inherit;
    padding: 0 2px;
    border-radius: 2px;
  }

  .modal-footer {
    padding: 12px 16px;
    border-top: 1px solid var(--border-primary);
    background: var(--bg-secondary);
    border-radius: 0 0 12px 12px;
  }

  .hint {
    font-size: 12px;
    color: var(--text-secondary);
  }

  .hint kbd {
    background: var(--btn-secondary-bg);
    padding: 2px 6px;
    border-radius: 4px;
    font-family: inherit;
    font-size: 11px;
    margin-right: 4px;
  }
</style>

// app/src/components/ui/QuickMove.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import * as api from '../../lib/api';
import type { SearchResult } from '../../lib/api';
import { useOutlineStore } from '../../store/outlineStore';

interface QuickMoveProps {
  isOpen: boolean;
  onClose: () => void;
  bulkMode?: boolean; // When true, move all selected nodes instead of focused node
}

function stripHtml(html: string): string {
  // Use regex to strip HTML tags - safer than innerHTML parsing
  return html
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .trim();
}

export function QuickMove({ isOpen, onClose, bulkMode = false }: QuickMoveProps) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<SearchResult[]>([]);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const [moving, setMoving] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // Get store state and actions
  const focusedId = useOutlineStore(state => state.focusedId);
  const nodes = useOutlineStore(state => state.nodes);
  const getNode = useOutlineStore(state => state.getNode);
  const moveNodeTo = useOutlineStore(state => state.moveNodeTo);
  const getSelectedNodes = useOutlineStore(state => state.getSelectedNodes);
  const selectedIds = useOutlineStore(state => state.selectedIds);
  const clearSelection = useOutlineStore(state => state.clearSelection);

  // Reset state when modal opens
  useEffect(() => {
    if (isOpen) {
      setQuery('');
      setResults([]);
      setSelectedIndex(0);
      setTimeout(() => inputRef.current?.focus(), 50);
    }
  }, [isOpen]);

  // Search when query changes
  useEffect(() => {
    if (query.trim().length === 0) {
      setResults([]);
      setSelectedIndex(0);
      return;
    }

    const timeoutId = setTimeout(async () => {
      setLoading(true);
      try {
        const searchResults = await api.search(query, undefined, 30);
        setResults(searchResults);
        setSelectedIndex(0);
      } finally {
        setLoading(false);
      }
    }, 150);

    return () => clearTimeout(timeoutId);
  }, [query]);

  // Scroll selected result into view
  useEffect(() => {
    if (results.length > 0) {
      const element = document.querySelector(`[data-move-index="${selectedIndex}"]`);
      element?.scrollIntoView({ block: 'nearest' });
    }
  }, [selectedIndex, results.length]);

  const handleClose = useCallback(() => {
    setQuery('');
    setResults([]);
    setSelectedIndex(0);
    onClose();
  }, [onClose]);

  const moveToNode = useCallback(async (targetNodeId: string) => {
    // Determine which nodes to move
    const nodesToMove = bulkMode && selectedIds.size > 0
      ? getSelectedNodes()
      : focusedId ? [getNode(focusedId)].filter(Boolean) : [];

    if (nodesToMove.length === 0) {
      handleClose();
      return;
    }

    // Don't allow moving a node to itself or its descendant
    const targetNodeIds = new Set([targetNodeId]);
    // Build set of all descendants of nodes being moved
    const isDescendant = (nodeId: string, ancestorIds: Set<string>): boolean => {
      let current = getNode(nodeId);
      while (current?.parent_id) {
        if (ancestorIds.has(current.parent_id)) return true;
        current = getNode(current.parent_id);
      }
      return false;
    };

    // Check if target is one of the nodes being moved or a descendant
    const moveNodeIds = new Set(nodesToMove.map(n => n!.id));
    if (moveNodeIds.has(targetNodeId) || isDescendant(targetNodeId, moveNodeIds)) {
      console.warn('Cannot move nodes to themselves or their descendants');
      handleClose();
      return;
    }

    setMoving(true);
    try {
      // Get current children count of target
      let targetChildren = nodes.filter(n => n.parent_id === targetNodeId);
      let newPosition = targetChildren.length;

      // Move nodes in order - this maintains their relative ordering
      for (const node of nodesToMove) {
        if (!node) continue;
        await moveNodeTo(node.id, targetNodeId, newPosition);
        newPosition++;
      }

      // Clear selection after bulk move
      if (bulkMode) {
        clearSelection();
      }

      handleClose();
    } catch (e) {
      console.error('Failed to move node(s):', e);
    } finally {
      setMoving(false);
    }
  }, [focusedId, bulkMode, selectedIds, getSelectedNodes, nodes, moveNodeTo, handleClose, getNode, clearSelection]);

  const selectCurrent = useCallback(() => {
    const result = results[selectedIndex];
    if (result) {
      moveToNode(result.node_id);
    }
  }, [results, selectedIndex, moveToNode]);

  // Keyboard handler
  useEffect(() => {
    if (!isOpen) return;

    const handleKeydown = (event: KeyboardEvent) => {
      switch (event.key) {
        case 'ArrowDown':
          event.preventDefault();
          setSelectedIndex(prev => Math.min(prev + 1, results.length - 1));
          break;
        case 'ArrowUp':
          event.preventDefault();
          setSelectedIndex(prev => Math.max(prev - 1, 0));
          break;
        case 'Enter':
          event.preventDefault();
          selectCurrent();
          break;
        case 'Escape':
          event.preventDefault();
          handleClose();
          break;
      }
    };

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  }, [isOpen, results.length, selectCurrent, handleClose]);

  const handleBackdropClick = useCallback((event: React.MouseEvent) => {
    if (event.target === event.currentTarget) {
      handleClose();
    }
  }, [handleClose]);

  // Get source node content for display
  const getSourceNodeContent = useCallback((): string => {
    if (bulkMode && selectedIds.size > 0) {
      const selected = getSelectedNodes();
      if (selected.length === 0) return '';
      if (selected.length === 1) {
        const text = stripHtml(selected[0].content);
        return text.length > 40 ? text.substring(0, 40) + '...' : text;
      }
      return `${selected.length} items`;
    }
    if (!focusedId) return '';
    const node = getNode(focusedId);
    if (!node) return '';
    const text = stripHtml(node.content);
    return text.length > 40 ? text.substring(0, 40) + '...' : text;
  }, [focusedId, bulkMode, selectedIds, getNode, getSelectedNodes]);

  if (!isOpen) {
    return null;
  }

  return (
    <div className="modal-backdrop" onClick={handleBackdropClick}>
      <div className="modal quick-move-modal">
        <div className="header-info">
          <span className="move-label">Move:</span>
          <span className="source-node">{getSourceNodeContent()}</span>
        </div>

        <div className="search-input-wrapper">
          <svg className="mode-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M5 9l7 7 7-7" />
          </svg>
          <input
            ref={inputRef}
            type="text"
            className="search-input"
            placeholder="Move to..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            disabled={moving}
          />
          {loading && <span className="loading-indicator">...</span>}
          {moving && <span className="loading-indicator">Moving...</span>}
        </div>

        <div className="results">
          {results.length === 0 && query.trim().length > 0 && !loading ? (
            <div className="no-results">No items found</div>
          ) : results.length === 0 && query.trim().length === 0 ? (
            <div className="hint-text">Search for a destination node...</div>
          ) : (
            results.map((result, index) => (
              <div
                key={result.node_id}
                className={`result ${index === selectedIndex ? 'selected' : ''}`}
                data-move-index={index}
                onClick={() => moveToNode(result.node_id)}
              >
                <div className="result-content">
                  {stripHtml(result.snippet)}
                </div>
              </div>
            ))
          )}
        </div>

        <div className="modal-footer">
          <span className="hint">
            <kbd>↑↓</kbd> Navigate
            <kbd>Enter</kbd> Move here
            <kbd>Esc</kbd> Cancel
          </span>
        </div>
      </div>
    </div>
  );
}

export default QuickMove;
