// app/src/lib/QuickNavigator.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import * as api from './api';
  import type { SearchResult, DocumentInfo } from './api';
  import { outline } from './outline.svelte';

  type NavigatorMode = 'files' | 'items';

  interface Props {
    isOpen: boolean;
    mode: NavigatorMode;
    onClose: () => void;
    onNavigate: (nodeId: string, documentId: string) => void;
  }

  let { isOpen, mode, onClose, onNavigate }: Props = $props();

  let query = $state('');
  let fileResults = $state<DocumentInfo[]>([]);
  let itemResults = $state<SearchResult[]>([]);
  let selectedIndex = $state(0);
  let loading = $state(false);
  let inputElement: HTMLInputElement | undefined = $state();
  let allDocuments = $state<DocumentInfo[]>([]);

  // Load documents when opened in file mode
  $effect(() => {
    if (isOpen && mode === 'files') {
      loadDocuments();
    }
  });

  async function loadDocuments() {
    try {
      allDocuments = await api.listDocuments();
      filterFiles();
    } catch (e) {
      console.error('Failed to load documents:', e);
    }
  }

  // Fuzzy filter for file names
  function fuzzyMatch(text: string, pattern: string): boolean {
    if (!pattern) return true;
    const textLower = text.toLowerCase();
    const patternLower = pattern.toLowerCase();

    // Simple substring match for now
    return textLower.includes(patternLower);
  }

  function filterFiles() {
    fileResults = allDocuments.filter(doc => fuzzyMatch(doc.title, query));
    selectedIndex = 0;
  }

  // Search when query changes
  let searchTimeout: ReturnType<typeof setTimeout> | undefined;

  $effect(() => {
    if (mode === 'files') {
      filterFiles();
    } else if (mode === 'items') {
      if (query.trim().length > 0) {
        clearTimeout(searchTimeout);
        searchTimeout = setTimeout(async () => {
          loading = true;
          try {
            itemResults = await api.search(query, undefined, 30);
            selectedIndex = 0;
          } finally {
            loading = false;
          }
        }, 150);
      } else {
        itemResults = [];
        selectedIndex = 0;
      }
    }
  });

  // Focus input when modal opens
  $effect(() => {
    if (isOpen && inputElement) {
      setTimeout(() => inputElement?.focus(), 50);
    }
  });

  function getResultCount(): number {
    return mode === 'files' ? fileResults.length : itemResults.length;
  }

  function handleKeydown(event: KeyboardEvent) {
    if (!isOpen) return;

    const resultCount = getResultCount();

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        selectedIndex = Math.min(selectedIndex + 1, resultCount - 1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        selectedIndex = Math.max(selectedIndex - 1, 0);
        break;
      case 'Enter':
        event.preventDefault();
        selectCurrent();
        break;
      case 'Escape':
        event.preventDefault();
        handleClose();
        break;
    }
  }

  function selectCurrent() {
    if (mode === 'files') {
      const doc = fileResults[selectedIndex];
      if (doc) {
        // Navigate to document (pass empty string for nodeId to indicate document level)
        onNavigate('', doc.id);
        handleClose();
      }
    } else {
      const result = itemResults[selectedIndex];
      if (result) {
        onNavigate(result.node_id, result.document_id);
        handleClose();
      }
    }
  }

  function selectFile(doc: DocumentInfo) {
    onNavigate('', doc.id);
    handleClose();
  }

  function selectItem(result: SearchResult) {
    onNavigate(result.node_id, result.document_id);
    handleClose();
  }

  function handleClose() {
    query = '';
    fileResults = [];
    itemResults = [];
    selectedIndex = 0;
    onClose();
  }

  function handleBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      handleClose();
    }
  }

  // Scroll selected result into view
  $effect(() => {
    if (getResultCount() > 0) {
      const element = document.querySelector(`[data-nav-index="${selectedIndex}"]`);
      element?.scrollIntoView({ block: 'nearest' });
    }
  });

  function getPlaceholder(): string {
    return mode === 'files' ? 'Go to document...' : 'Go to item...';
  }

  function getModeIcon(): string {
    return mode === 'files' ? 'file' : 'item';
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if isOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal-backdrop" onclick={handleBackdropClick}>
    <div class="modal">
      <div class="search-input-wrapper">
        {#if mode === 'files'}
          <svg class="mode-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
            <polyline points="14 2 14 8 20 8" />
          </svg>
        {:else}
          <svg class="mode-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10" />
            <path d="M8 12h8" />
            <path d="M12 8v8" />
          </svg>
        {/if}
        <input
          bind:this={inputElement}
          type="text"
          class="search-input"
          placeholder={getPlaceholder()}
          bind:value={query}
        />
        {#if loading}
          <span class="loading-indicator">...</span>
        {/if}
      </div>

      <div class="results">
        {#if mode === 'files'}
          {#if fileResults.length === 0}
            <div class="no-results">No documents found</div>
          {:else}
            {#each fileResults as doc, index}
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <!-- svelte-ignore a11y_no_static_element_interactions -->
              <div
                class="result"
                class:selected={index === selectedIndex}
                data-nav-index={index}
                onclick={() => selectFile(doc)}
              >
                <div class="result-title">{doc.title}</div>
                <div class="result-meta">{doc.node_count} items</div>
              </div>
            {/each}
          {/if}
        {:else}
          {#if itemResults.length === 0 && query.trim().length > 0 && !loading}
            <div class="no-results">No items found</div>
          {:else if itemResults.length === 0 && query.trim().length === 0}
            <div class="hint-text">Type to search all items...</div>
          {:else}
            {#each itemResults as result, index}
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <!-- svelte-ignore a11y_no_static_element_interactions -->
              <div
                class="result"
                class:selected={index === selectedIndex}
                data-nav-index={index}
                onclick={() => selectItem(result)}
              >
                <div class="result-content">
                  {@html result.snippet}
                </div>
              </div>
            {/each}
          {/if}
        {/if}
      </div>

      <div class="modal-footer">
        <span class="hint">
          <kbd>↑↓</kbd> Navigate
          <kbd>Enter</kbd> Select
          <kbd>Esc</kbd> Close
        </span>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: flex-start;
    justify-content: center;
    padding-top: 100px;
    z-index: 1000;
  }

  .modal {
    background: white;
    border-radius: 12px;
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
    width: 500px;
    max-width: 90vw;
    max-height: 60vh;
    display: flex;
    flex-direction: column;
  }

  .search-input-wrapper {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 16px;
    border-bottom: 1px solid #e0e0e0;
  }

  .mode-icon {
    width: 20px;
    height: 20px;
    color: #666;
    flex-shrink: 0;
  }

  .search-input {
    flex: 1;
    border: none;
    outline: none;
    font-size: 16px;
    background: transparent;
  }

  .search-input::placeholder {
    color: #999;
  }

  .loading-indicator {
    color: #666;
    font-size: 14px;
  }

  .results {
    flex: 1;
    overflow-y: auto;
    max-height: 350px;
  }

  .no-results, .hint-text {
    padding: 24px;
    text-align: center;
    color: #666;
  }

  .result {
    padding: 12px 16px;
    cursor: pointer;
    border-bottom: 1px solid #f0f0f0;
  }

  .result:last-child {
    border-bottom: none;
  }

  .result:hover,
  .result.selected {
    background: #f5f5f5;
  }

  .result.selected {
    background: #e3f2fd;
  }

  .result-title {
    font-size: 14px;
    font-weight: 500;
    color: #333;
  }

  .result-meta {
    font-size: 12px;
    color: #666;
    margin-top: 2px;
  }

  .result-content {
    font-size: 14px;
    line-height: 1.5;
    color: #333;
  }

  .result-content :global(mark) {
    background: #fff59d;
    color: inherit;
    padding: 0 2px;
    border-radius: 2px;
  }

  .modal-footer {
    padding: 12px 16px;
    border-top: 1px solid #e0e0e0;
    background: #fafafa;
    border-radius: 0 0 12px 12px;
  }

  .hint {
    font-size: 12px;
    color: #666;
  }

  .hint kbd {
    background: #e0e0e0;
    padding: 2px 6px;
    border-radius: 4px;
    font-family: inherit;
    font-size: 11px;
    margin-right: 4px;
  }
</style>

// app/src/components/ui/QuickNavigator.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import * as api from '../../lib/api';
import type { SearchResult, DocumentInfo } from '../../lib/api';

type NavigatorMode = 'files' | 'items';

interface QuickNavigatorProps {
  isOpen: boolean;
  mode: NavigatorMode;
  onClose: () => void;
  onNavigate: (nodeId: string, documentId: string) => void;
}

function stripHtml(html: string): string {
  const div = document.createElement('div');
  div.textContent = html;
  return div.textContent || '';
}

export function QuickNavigator({ isOpen, mode, onClose, onNavigate }: QuickNavigatorProps) {
  const [query, setQuery] = useState('');
  const [fileResults, setFileResults] = useState<DocumentInfo[]>([]);
  const [itemResults, setItemResults] = useState<SearchResult[]>([]);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const [allDocuments, setAllDocuments] = useState<DocumentInfo[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);

  // Load documents when opened in file mode
  useEffect(() => {
    if (isOpen && mode === 'files') {
      loadDocuments();
    }
  }, [isOpen, mode]);

  async function loadDocuments() {
    try {
      const docs = await api.listDocuments();
      setAllDocuments(docs);
    } catch (e) {
      console.error('Failed to load documents:', e);
    }
  }

  // Fuzzy filter for file names
  function fuzzyMatch(text: string, pattern: string): boolean {
    if (!pattern) return true;
    const textLower = text.toLowerCase();
    const patternLower = pattern.toLowerCase();
    return textLower.includes(patternLower);
  }

  // Filter files when query or documents change
  useEffect(() => {
    if (mode === 'files') {
      const filtered = allDocuments.filter(doc => fuzzyMatch(doc.title, query));
      setFileResults(filtered);
      setSelectedIndex(0);
    }
  }, [mode, query, allDocuments]);

  // Search items when query changes
  useEffect(() => {
    if (mode !== 'items') return;
    if (query.trim().length === 0) {
      setItemResults([]);
      setSelectedIndex(0);
      return;
    }

    const timeoutId = setTimeout(async () => {
      setLoading(true);
      try {
        const results = await api.search(query, undefined, 30);
        setItemResults(results);
        setSelectedIndex(0);
      } finally {
        setLoading(false);
      }
    }, 150);

    return () => clearTimeout(timeoutId);
  }, [mode, query]);

  // Focus input when modal opens
  useEffect(() => {
    if (isOpen && inputRef.current) {
      setTimeout(() => inputRef.current?.focus(), 50);
    }
  }, [isOpen]);

  // Scroll selected result into view
  useEffect(() => {
    const count = mode === 'files' ? fileResults.length : itemResults.length;
    if (count > 0) {
      const element = document.querySelector(`[data-nav-index="${selectedIndex}"]`);
      element?.scrollIntoView({ block: 'nearest' });
    }
  }, [selectedIndex, mode, fileResults.length, itemResults.length]);

  const handleClose = useCallback(() => {
    setQuery('');
    setFileResults([]);
    setItemResults([]);
    setSelectedIndex(0);
    onClose();
  }, [onClose]);

  const selectFile = useCallback((doc: DocumentInfo) => {
    onNavigate('', doc.id);
    handleClose();
  }, [onNavigate, handleClose]);

  const selectItem = useCallback((result: SearchResult) => {
    onNavigate(result.node_id, result.document_id);
    handleClose();
  }, [onNavigate, handleClose]);

  const selectCurrent = useCallback(() => {
    if (mode === 'files') {
      const doc = fileResults[selectedIndex];
      if (doc) {
        selectFile(doc);
      }
    } else {
      const result = itemResults[selectedIndex];
      if (result) {
        selectItem(result);
      }
    }
  }, [mode, fileResults, itemResults, selectedIndex, selectFile, selectItem]);

  // Keyboard handler
  useEffect(() => {
    if (!isOpen) return;

    const handleKeydown = (event: KeyboardEvent) => {
      const resultCount = mode === 'files' ? fileResults.length : itemResults.length;

      switch (event.key) {
        case 'ArrowDown':
          event.preventDefault();
          setSelectedIndex(prev => Math.min(prev + 1, resultCount - 1));
          break;
        case 'ArrowUp':
          event.preventDefault();
          setSelectedIndex(prev => Math.max(prev - 1, 0));
          break;
        case 'Enter':
          event.preventDefault();
          selectCurrent();
          break;
        case 'Escape':
          event.preventDefault();
          handleClose();
          break;
      }
    };

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  }, [isOpen, mode, fileResults.length, itemResults.length, selectCurrent, handleClose]);

  const handleBackdropClick = useCallback((event: React.MouseEvent) => {
    if (event.target === event.currentTarget) {
      handleClose();
    }
  }, [handleClose]);

  if (!isOpen) {
    return null;
  }

  const placeholder = mode === 'files' ? 'Go to document...' : 'Go to item...';

  return (
    <div className="modal-backdrop" onClick={handleBackdropClick}>
      <div className="modal quick-navigator-modal">
        <div className="search-input-wrapper">
          {mode === 'files' ? (
            <svg className="mode-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
            </svg>
          ) : (
            <svg className="mode-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <path d="M8 12h8" />
              <path d="M12 8v8" />
            </svg>
          )}
          <input
            ref={inputRef}
            type="text"
            className="search-input"
            placeholder={placeholder}
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
          {loading && <span className="loading-indicator">...</span>}
        </div>

        <div className="results">
          {mode === 'files' ? (
            fileResults.length === 0 ? (
              <div className="no-results">No documents found</div>
            ) : (
              fileResults.map((doc, index) => (
                <div
                  key={doc.id}
                  className={`result ${index === selectedIndex ? 'selected' : ''}`}
                  data-nav-index={index}
                  onClick={() => selectFile(doc)}
                >
                  <div className="result-title">{doc.title}</div>
                  <div className="result-meta">{doc.node_count} items</div>
                </div>
              ))
            )
          ) : (
            <>
              {itemResults.length === 0 && query.trim().length > 0 && !loading && (
                <div className="no-results">No items found</div>
              )}
              {itemResults.length === 0 && query.trim().length === 0 && (
                <div className="hint-text">Type to search all items...</div>
              )}
              {itemResults.map((result, index) => (
                <div
                  key={result.node_id}
                  className={`result ${index === selectedIndex ? 'selected' : ''}`}
                  data-nav-index={index}
                  onClick={() => selectItem(result)}
                >
                  <div className="result-content">
                    {stripHtml(result.snippet)}
                  </div>
                </div>
              ))}
            </>
          )}
        </div>

        <div className="modal-footer">
          <span className="hint">
            <kbd>↑↓</kbd> Navigate
            <kbd>Enter</kbd> Select
            <kbd>Esc</kbd> Close
          </span>
        </div>
      </div>
    </div>
  );
}

export default QuickNavigator;
