// app/src/lib/SearchModal.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import * as api from './api';
  import type { SearchResult } from './api';
  import { outline } from './outline.svelte';

  interface Props {
    isOpen: boolean;
    documentScope?: string; // If set, search only within this document
    initialQuery?: string; // Pre-fill search query
    onClose: () => void;
    onNavigate: (nodeId: string, documentId: string) => void;
  }

  let { isOpen, documentScope, initialQuery = '', onClose, onNavigate }: Props = $props();

  let query = $state(initialQuery);

  // Update query when initialQuery changes (e.g., hashtag click)
  $effect(() => {
    if (initialQuery && isOpen) {
      query = initialQuery;
    }
  });
  let results = $state<SearchResult[]>([]);
  let selectedIndex = $state(0);
  let loading = $state(false);
  let inputElement: HTMLInputElement | undefined = $state();

  // Search when query changes
  let searchTimeout: ReturnType<typeof setTimeout> | undefined;

  $effect(() => {
    if (query.trim().length > 0) {
      // Debounce search
      clearTimeout(searchTimeout);
      searchTimeout = setTimeout(async () => {
        loading = true;
        try {
          results = await api.search(query, documentScope);
          selectedIndex = 0;
        } finally {
          loading = false;
        }
      }, 150);
    } else {
      results = [];
      selectedIndex = 0;
    }
  });

  // Focus input when modal opens
  $effect(() => {
    if (isOpen && inputElement) {
      setTimeout(() => inputElement?.focus(), 50);
    }
  });

  function handleKeydown(event: KeyboardEvent) {
    if (!isOpen) return;

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        selectedIndex = Math.min(selectedIndex + 1, results.length - 1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        selectedIndex = Math.max(selectedIndex - 1, 0);
        break;
      case 'Enter':
        event.preventDefault();
        if (results[selectedIndex]) {
          selectResult(results[selectedIndex]);
        }
        break;
      case 'Escape':
        event.preventDefault();
        handleClose();
        break;
    }
  }

  function selectResult(result: SearchResult) {
    onNavigate(result.node_id, result.document_id);
    handleClose();
  }

  function handleClose() {
    query = '';
    results = [];
    selectedIndex = 0;
    onClose();
  }

  function handleBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      handleClose();
    }
  }

  // Scroll selected result into view
  $effect(() => {
    if (results.length > 0) {
      const element = document.querySelector(`[data-search-index="${selectedIndex}"]`);
      element?.scrollIntoView({ block: 'nearest' });
    }
  });
</script>

<svelte:window onkeydown={handleKeydown} />

{#if isOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal-backdrop" onclick={handleBackdropClick}>
    <div class="modal">
      <div class="search-input-wrapper">
        <svg class="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="11" cy="11" r="8" />
          <path d="m21 21-4.35-4.35" />
        </svg>
        <input
          bind:this={inputElement}
          type="text"
          class="search-input"
          placeholder={documentScope ? "Search in this document..." : "Search all documents..."}
          bind:value={query}
        />
        {#if loading}
          <span class="loading-indicator">...</span>
        {/if}
      </div>

      <div class="results">
        {#if results.length === 0 && query.trim().length > 0 && !loading}
          <div class="no-results">No results found</div>
        {:else}
          {#each results as result, index}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div
              class="result"
              class:selected={index === selectedIndex}
              data-search-index={index}
              onclick={() => selectResult(result)}
            >
              <div class="result-content">
                {@html result.snippet}
              </div>
              {#if result.note}
                <div class="result-note">{result.note}</div>
              {/if}
            </div>
          {/each}
        {/if}
      </div>

      <div class="modal-footer">
        <span class="hint">
          <kbd>↑↓</kbd> Navigate
          <kbd>Enter</kbd> Select
          <kbd>Esc</kbd> Close
        </span>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: flex-start;
    justify-content: center;
    padding-top: 100px;
    z-index: 1000;
  }

  .modal {
    background: white;
    border-radius: 12px;
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
    width: 600px;
    max-width: 90vw;
    max-height: 70vh;
    display: flex;
    flex-direction: column;
  }

  .search-input-wrapper {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 16px;
    border-bottom: 1px solid #e0e0e0;
  }

  .search-icon {
    width: 20px;
    height: 20px;
    color: #666;
    flex-shrink: 0;
  }

  .search-input {
    flex: 1;
    border: none;
    outline: none;
    font-size: 16px;
    background: transparent;
  }

  .search-input::placeholder {
    color: #999;
  }

  .loading-indicator {
    color: #666;
    font-size: 14px;
  }

  .results {
    flex: 1;
    overflow-y: auto;
    max-height: 400px;
  }

  .no-results {
    padding: 24px;
    text-align: center;
    color: #666;
  }

  .result {
    padding: 12px 16px;
    cursor: pointer;
    border-bottom: 1px solid #f0f0f0;
  }

  .result:last-child {
    border-bottom: none;
  }

  .result:hover,
  .result.selected {
    background: #f5f5f5;
  }

  .result.selected {
    background: #e3f2fd;
  }

  .result-content {
    font-size: 14px;
    line-height: 1.5;
    color: #333;
  }

  .result-content :global(mark) {
    background: #fff59d;
    color: inherit;
    padding: 0 2px;
    border-radius: 2px;
  }

  .result-note {
    font-size: 12px;
    color: #666;
    margin-top: 4px;
  }

  .modal-footer {
    padding: 12px 16px;
    border-top: 1px solid #e0e0e0;
    background: #fafafa;
    border-radius: 0 0 12px 12px;
  }

  .hint {
    font-size: 12px;
    color: #666;
  }

  .hint kbd {
    background: #e0e0e0;
    padding: 2px 6px;
    border-radius: 4px;
    font-family: inherit;
    font-size: 11px;
    margin-right: 4px;
  }
</style>

// app/src/components/ui/SearchModal.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import * as api from '../../lib/api';
import type { SearchResult } from '../../lib/api';

interface SearchModalProps {
  isOpen: boolean;
  documentScope?: string; // If set, search only within this document
  initialQuery?: string; // Pre-fill search query
  onClose: () => void;
  onNavigate: (nodeId: string, documentId: string) => void;
}

function stripHtml(html: string): string {
  const div = document.createElement('div');
  div.textContent = html;
  return div.textContent || '';
}

export function SearchModal({ isOpen, documentScope, initialQuery = '', onClose, onNavigate }: SearchModalProps) {
  const [query, setQuery] = useState(initialQuery);
  const [results, setResults] = useState<SearchResult[]>([]);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // Update query when initialQuery changes (e.g., hashtag click)
  useEffect(() => {
    if (initialQuery && isOpen) {
      setQuery(initialQuery);
    }
  }, [initialQuery, isOpen]);

  // Search when query changes
  useEffect(() => {
    if (query.trim().length > 0) {
      const timeoutId = setTimeout(async () => {
        setLoading(true);
        try {
          const searchResults = await api.search(query, documentScope);
          setResults(searchResults);
          setSelectedIndex(0);
        } finally {
          setLoading(false);
        }
      }, 150);

      return () => clearTimeout(timeoutId);
    } else {
      setResults([]);
      setSelectedIndex(0);
    }
  }, [query, documentScope]);

  // Focus input when modal opens
  useEffect(() => {
    if (isOpen && inputRef.current) {
      setTimeout(() => inputRef.current?.focus(), 50);
    }
  }, [isOpen]);

  // Scroll selected result into view
  useEffect(() => {
    if (results.length > 0) {
      const element = document.querySelector(`[data-search-index="${selectedIndex}"]`);
      element?.scrollIntoView({ block: 'nearest' });
    }
  }, [selectedIndex, results.length]);

  const selectResult = useCallback((result: SearchResult) => {
    onNavigate(result.node_id, result.document_id);
    handleClose();
  }, [onNavigate]);

  const handleClose = useCallback(() => {
    setQuery('');
    setResults([]);
    setSelectedIndex(0);
    onClose();
  }, [onClose]);

  // Keyboard handler
  useEffect(() => {
    if (!isOpen) return;

    const handleKeydown = (event: KeyboardEvent) => {
      switch (event.key) {
        case 'ArrowDown':
          event.preventDefault();
          setSelectedIndex(prev => Math.min(prev + 1, results.length - 1));
          break;
        case 'ArrowUp':
          event.preventDefault();
          setSelectedIndex(prev => Math.max(prev - 1, 0));
          break;
        case 'Enter':
          event.preventDefault();
          if (results[selectedIndex]) {
            selectResult(results[selectedIndex]);
          }
          break;
        case 'Escape':
          event.preventDefault();
          handleClose();
          break;
      }
    };

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  }, [isOpen, results, selectedIndex, selectResult, handleClose]);

  const handleBackdropClick = useCallback((event: React.MouseEvent) => {
    if (event.target === event.currentTarget) {
      handleClose();
    }
  }, [handleClose]);

  if (!isOpen) {
    return null;
  }

  return (
    <div className="modal-backdrop" onClick={handleBackdropClick}>
      <div className="modal search-modal">
        <div className="search-input-wrapper">
          <svg className="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.35-4.35" />
          </svg>
          <input
            ref={inputRef}
            type="text"
            className="search-input"
            placeholder={documentScope ? "Search in this document..." : "Search all documents..."}
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
          {loading && <span className="loading-indicator">...</span>}
        </div>

        <div className="results">
          {results.length === 0 && query.trim().length > 0 && !loading ? (
            <div className="no-results">No results found</div>
          ) : (
            results.map((result, index) => (
              <div
                key={result.node_id}
                className={`result ${index === selectedIndex ? 'selected' : ''}`}
                data-search-index={index}
                onClick={() => selectResult(result)}
              >
                <div className="result-content">
                  {stripHtml(result.snippet)}
                </div>
                {result.note && (
                  <div className="result-note">{result.note}</div>
                )}
              </div>
            ))
          )}
        </div>

        <div className="modal-footer">
          <span className="hint">
            <kbd>↑↓</kbd> Navigate
            <kbd>Enter</kbd> Select
            <kbd>Esc</kbd> Close
          </span>
        </div>
      </div>
    </div>
  );
}

export default SearchModal;
