// app/src/lib/OutlineItem.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { Editor } from '@tiptap/core';
  import StarterKit from '@tiptap/starter-kit';
  import { Plugin, PluginKey } from '@tiptap/pm/state';
  import { outline } from './outline.svelte';
  import type { TreeNode } from './types';
  import OutlineItem from './OutlineItem.svelte';
  import { WikiLink } from './WikiLink';
  import WikiLinkSuggestion from './WikiLinkSuggestion.svelte';
  import BacklinksPanel from './BacklinksPanel.svelte';
  import DateBadge from './DateBadge.svelte';
  import DatePicker from './DatePicker.svelte';
  import RecurrencePicker from './RecurrencePicker.svelte';

  interface Props {
    item: TreeNode;
    onNavigateToNode?: (nodeId: string) => void;
  }

  let { item, onNavigateToNode }: Props = $props();

  let editor: Editor | undefined = $state();
  let editorElement: HTMLDivElement | undefined = $state();
  let tabHandler: ((e: KeyboardEvent) => void) | undefined;

  // Wiki link suggestion state
  let showWikiLinkSuggestion = $state(false);
  let wikiLinkQuery = $state('');
  let wikiLinkRange = $state<{ from: number; to: number } | null>(null);
  let suggestionPosition = $state({ x: 0, y: 0 });

  // Date picker state
  let showDatePicker = $state(false);
  let datePickerPosition = $state({ x: 0, y: 0 });

  // Recurrence picker state
  let showRecurrencePicker = $state(false);
  let recurrencePickerPosition = $state({ x: 0, y: 0 });

  // Reactive checks
  let isFocused = $derived(outline.focusedId === item.node.id);

  // Sync content from store to editor when it changes externally
  $effect(() => {
    if (editor && !editor.isFocused) {
      const currentContent = editor.getHTML();
      if (currentContent !== item.node.content) {
        editor.commands.setContent(item.node.content || '');
      }
    }
  });

  // Focus editor when this node becomes focused
  $effect(() => {
    if (isFocused && editor) {
      // Small delay to ensure editor is ready
      setTimeout(() => {
        editor?.commands.focus('end');
      }, 0);
    }
  });

  onMount(() => {
    if (!editorElement) return;

    // Capture Tab before browser focus navigation - must use capture phase
    tabHandler = (event: KeyboardEvent) => {
      if (event.key === 'Tab') {
        event.preventDefault();
        event.stopPropagation();
        if (event.shiftKey) {
          outline.outdentNode(item.node.id);
        } else {
          outline.indentNode(item.node.id);
        }
      }
    };
    editorElement.addEventListener('keydown', tabHandler, { capture: true });

    // Create plugin for [[ detection
    const wikiLinkInputPlugin = new Plugin({
      key: new PluginKey('wikiLinkInput'),
      props: {
        handleTextInput: (view, from, to, text) => {
          const state = view.state;
          const prevChar = from > 0 ? state.doc.textBetween(from - 1, from) : '';

          // Detect [[ trigger
          if (text === '[' && prevChar === '[') {
            showWikiLinkSuggestion = true;
            wikiLinkQuery = '';
            wikiLinkRange = { from: from - 1, to: from + 1 };
            updateSuggestionPosition(view);
            return false;
          }

          // If suggestion is active, update query
          if (showWikiLinkSuggestion && wikiLinkRange) {
            // Calculate current query
            const queryStart = wikiLinkRange.from + 2;
            const currentQuery = state.doc.textBetween(queryStart, from) + text;

            // Check for ]] to close
            if (text === ']' && currentQuery.endsWith(']')) {
              showWikiLinkSuggestion = false;
              wikiLinkRange = null;
              return false;
            }

            wikiLinkQuery = currentQuery;
            wikiLinkRange = { ...wikiLinkRange, to: from + text.length + 1 };
          }

          return false;
        },
      },
    });

    function updateSuggestionPosition(view: any) {
      const coords = view.coordsAtPos(view.state.selection.from);
      suggestionPosition = {
        x: coords.left,
        y: coords.bottom + 5,
      };
    }

    editor = new Editor({
      element: editorElement,
      extensions: [
        StarterKit.configure({
          // Disable multi-line features for single-line items
          heading: false,
          bulletList: false,
          orderedList: false,
          blockquote: false,
          codeBlock: false,
          horizontalRule: false,
          hardBreak: false
        }),
        WikiLink.configure({
          onNavigate: (nodeId: string) => {
            if (onNavigateToNode) {
              onNavigateToNode(nodeId);
            } else {
              outline.focus(nodeId);
            }
          },
        }),
      ],
      content: item.node.content || '',
      editorProps: {
        attributes: {
          class: 'outline-editor'
        },
        handleKeyDown: (view, event) => {
          const mod = event.ctrlKey || event.metaKey;
          const nodeId = item.node.id;

          // === TAB HANDLING (must be first to prevent browser focus navigation) ===

          // Tab: indent, Shift+Tab: outdent
          if (event.key === 'Tab') {
            event.preventDefault();
            event.stopPropagation();
            if (event.shiftKey) {
              outline.outdentNode(nodeId);
            } else {
              outline.indentNode(nodeId);
            }
            return true;
          }

          // Handle wiki link suggestion navigation
          if (showWikiLinkSuggestion) {
            if (event.key === 'Escape') {
              showWikiLinkSuggestion = false;
              wikiLinkRange = null;
              return true;
            }
            // Let ArrowUp/Down/Enter pass to suggestion component
            if (['ArrowUp', 'ArrowDown', 'Enter'].includes(event.key)) {
              return false; // Let window handler catch it
            }
          }

          // === EDITING ===

          // Enter: add sibling below
          if (event.key === 'Enter' && !mod && !event.shiftKey) {
            event.preventDefault();
            outline.addSiblingAfter(nodeId);
            return true;
          }

          // Ctrl+Shift+Backspace: delete item
          if (event.key === 'Backspace' && mod && event.shiftKey) {
            event.preventDefault();
            outline.deleteNode(nodeId);
            return true;
          }

          // Backspace at start of empty node: delete
          if (event.key === 'Backspace' && !mod && !event.shiftKey) {
            const { from } = view.state.selection;
            const isEmpty = view.state.doc.textContent.length === 0;
            if (from === 1 && isEmpty) {
              event.preventDefault();
              outline.deleteNode(nodeId);
              return true;
            }
          }

          // === NAVIGATION ===

          // Up arrow: previous node
          if (event.key === 'ArrowUp' && !mod) {
            event.preventDefault();
            outline.moveToPrevious();
            return true;
          }

          // Down arrow: next node
          if (event.key === 'ArrowDown' && !mod) {
            event.preventDefault();
            outline.moveToNext();
            return true;
          }

          // Ctrl+Up: swap with previous sibling
          if (event.key === 'ArrowUp' && mod && !event.shiftKey) {
            event.preventDefault();
            outline.swapWithPrevious(nodeId);
            return true;
          }

          // Ctrl+Down: swap with next sibling
          if (event.key === 'ArrowDown' && mod && !event.shiftKey) {
            event.preventDefault();
            outline.swapWithNext(nodeId);
            return true;
          }

          // === COLLAPSE ===

          // Ctrl+. : toggle collapse
          if (event.key === '.' && mod) {
            event.preventDefault();
            outline.toggleCollapse(nodeId);
            return true;
          }

          // === CHECKBOX ===

          // Ctrl+Enter: toggle checkbox (if checkbox type)
          if (event.key === 'Enter' && mod && !event.shiftKey) {
            event.preventDefault();
            const node = outline.getNode(nodeId);
            if (node?.node_type === 'checkbox') {
              outline.toggleCheckbox(nodeId);
            }
            return true;
          }

          // Ctrl+Shift+C: toggle node type (bullet <-> checkbox)
          if (event.key === 'c' && mod && event.shiftKey) {
            event.preventDefault();
            outline.toggleNodeType(nodeId);
            return true;
          }

          // === DATE ===

          // Ctrl+D: open date picker
          if (event.key === 'd' && mod && !event.shiftKey) {
            event.preventDefault();
            openDatePicker(view);
            return true;
          }

          // Ctrl+Shift+D: clear date
          if (event.key === 'd' && mod && event.shiftKey) {
            event.preventDefault();
            outline.clearDate(nodeId);
            return true;
          }

          // Ctrl+R: open recurrence picker
          if (event.key === 'r' && mod && !event.shiftKey) {
            event.preventDefault();
            openRecurrencePicker(view);
            return true;
          }

          return false;
        }
      },
      onUpdate: ({ editor }) => {
        outline.updateContent(item.node.id, editor.getHTML());
      },
      onFocus: () => {
        outline.focus(item.node.id);
      }
    });
  });

  onDestroy(() => {
    if (editorElement && tabHandler) {
      editorElement.removeEventListener('keydown', tabHandler, { capture: true });
    }
    editor?.destroy();
  });

  function handleCollapseClick() {
    outline.toggleCollapse(item.node.id);
  }

  function handleCheckboxClick(e: MouseEvent) {
    e.preventDefault();
    e.stopPropagation();
    outline.toggleCheckbox(item.node.id);
  }

  function openDatePicker(view?: any) {
    if (view) {
      const coords = view.coordsAtPos(view.state.selection.from);
      datePickerPosition = { x: coords.left, y: coords.bottom + 5 };
    } else if (editorElement) {
      const rect = editorElement.getBoundingClientRect();
      datePickerPosition = { x: rect.left, y: rect.bottom + 5 };
    }
    showDatePicker = true;
  }

  function handleDateBadgeClick() {
    openDatePicker();
  }

  function handleDateSelect(date: string | null) {
    outline.setDate(item.node.id, date);
    showDatePicker = false;
  }

  function handleDatePickerClose() {
    showDatePicker = false;
  }

  function openRecurrencePicker(view?: any) {
    if (view) {
      const coords = view.coordsAtPos(view.state.selection.from);
      recurrencePickerPosition = { x: coords.left, y: coords.bottom + 5 };
    } else if (editorElement) {
      const rect = editorElement.getBoundingClientRect();
      recurrencePickerPosition = { x: rect.left, y: rect.bottom + 5 };
    }
    showRecurrencePicker = true;
  }

  function handleRecurrenceSelect(rrule: string | null) {
    outline.setRecurrence(item.node.id, rrule);
    showRecurrencePicker = false;
  }

  function handleRecurrencePickerClose() {
    showRecurrencePicker = false;
  }

  function handleWikiLinkSelect(nodeId: string, displayText: string) {
    if (!editor || !wikiLinkRange) return;

    // Delete the [[query text and insert the wiki link
    editor
      .chain()
      .focus()
      .deleteRange(wikiLinkRange)
      .insertWikiLink(nodeId, displayText)
      .run();

    showWikiLinkSuggestion = false;
    wikiLinkRange = null;
  }

  function handleWikiLinkClose() {
    showWikiLinkSuggestion = false;
    wikiLinkRange = null;
  }
</script>

<div class="outline-item" class:focused={isFocused} class:checked={item.node.is_checked} style="margin-left: {item.depth * 24}px">
  <div class="item-row">
    {#if item.node.node_type === 'checkbox'}
      <button
        class="checkbox-btn"
        class:checked={item.node.is_checked}
        onclick={handleCheckboxClick}
        tabindex="-1"
        aria-label={item.node.is_checked ? 'Mark incomplete' : 'Mark complete'}
      >
        {#if item.node.is_checked}
          <span class="checkbox-icon checked">✓</span>
        {:else}
          <span class="checkbox-icon"></span>
        {/if}
      </button>
    {:else}
      <button
        class="collapse-btn"
        class:has-children={item.hasChildren}
        class:collapsed={item.node.collapsed}
        onclick={handleCollapseClick}
        tabindex="-1"
      >
        {#if item.hasChildren}
          <span class="collapse-icon">{item.node.collapsed ? '▶' : '▼'}</span>
        {:else}
          <span class="bullet">•</span>
        {/if}
      </button>
    {/if}

    <div class="editor-wrapper" bind:this={editorElement}></div>

    {#if item.node.date_recurrence}
      <span class="recurrence-indicator" title="Recurring: {item.node.date_recurrence}">🔄</span>
    {/if}

    {#if item.node.date}
      <DateBadge
        date={item.node.date}
        isChecked={item.node.is_checked}
        onclick={handleDateBadgeClick}
      />
    {/if}
  </div>

  {#if isFocused}
    <BacklinksPanel
      nodeId={item.node.id}
      onNavigate={(nodeId) => onNavigateToNode ? onNavigateToNode(nodeId) : outline.focus(nodeId)}
    />
  {/if}

  {#if item.hasChildren && !item.node.collapsed}
    <div class="children">
      {#each item.children as child (child.node.id)}
        <OutlineItem item={child} {onNavigateToNode} />
      {/each}
    </div>
  {/if}
</div>

{#if showWikiLinkSuggestion}
  <WikiLinkSuggestion
    query={wikiLinkQuery}
    position={suggestionPosition}
    onSelect={handleWikiLinkSelect}
    onClose={handleWikiLinkClose}
  />
{/if}

{#if showDatePicker}
  <DatePicker
    position={datePickerPosition}
    currentDate={item.node.date}
    onSelect={handleDateSelect}
    onClose={handleDatePickerClose}
  />
{/if}

{#if showRecurrencePicker}
  <RecurrencePicker
    position={recurrencePickerPosition}
    currentRecurrence={item.node.date_recurrence}
    onSelect={handleRecurrenceSelect}
    onClose={handleRecurrencePickerClose}
  />
{/if}

<style>
  .item-row {
    display: flex;
    align-items: flex-start;
    padding: 2px 0;
    border-radius: 4px;
    transition: background-color 0.1s;
  }

  .focused .item-row {
    background-color: rgba(59, 130, 246, 0.1);
  }

  .collapse-btn {
    width: 20px;
    height: 24px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: none;
    border: none;
    cursor: pointer;
    color: #666;
    font-size: 10px;
    flex-shrink: 0;
    padding: 0;
  }

  .collapse-btn:hover {
    color: #333;
  }

  .collapse-btn.has-children {
    cursor: pointer;
  }

  .collapse-icon {
    transition: transform 0.15s;
  }

  .bullet {
    font-size: 14px;
    color: #999;
  }

  .checkbox-btn {
    width: 20px;
    height: 24px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: none;
    border: none;
    cursor: pointer;
    flex-shrink: 0;
    padding: 0;
  }

  .checkbox-icon {
    width: 14px;
    height: 14px;
    border: 2px solid #999;
    border-radius: 3px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 10px;
    color: transparent;
    background: white;
    transition: all 0.15s;
  }

  .checkbox-btn:hover .checkbox-icon {
    border-color: #666;
  }

  .checkbox-icon.checked {
    background: #4caf50;
    border-color: #4caf50;
    color: white;
  }

  /* Strikethrough for checked items */
  .outline-item.checked .editor-wrapper :global(.outline-editor) {
    text-decoration: line-through;
    color: #888;
  }

  .recurrence-indicator {
    font-size: 12px;
    margin-left: 4px;
    cursor: default;
    opacity: 0.7;
  }

  .recurrence-indicator:hover {
    opacity: 1;
  }

  .editor-wrapper {
    flex: 1;
    min-width: 0;
  }

  .editor-wrapper :global(.outline-editor) {
    outline: none;
    min-height: 24px;
    line-height: 24px;
  }

  .editor-wrapper :global(.outline-editor p) {
    margin: 0;
  }

  .editor-wrapper :global(.outline-editor strong) {
    font-weight: 600;
  }

  .editor-wrapper :global(.outline-editor em) {
    font-style: italic;
  }

  .editor-wrapper :global(.outline-editor code) {
    background: #f0f0f0;
    padding: 1px 4px;
    border-radius: 3px;
    font-family: 'SF Mono', Monaco, monospace;
    font-size: 0.9em;
  }

  .editor-wrapper :global(.wiki-link) {
    display: inline-flex;
    align-items: center;
    background: #e3f2fd;
    color: #1976d2;
    padding: 1px 8px;
    border-radius: 12px;
    font-size: 0.9em;
    cursor: pointer;
    text-decoration: none;
    margin: 0 2px;
  }

  .editor-wrapper :global(.wiki-link:hover) {
    background: #bbdefb;
  }

  .children {
    /* Children indentation handled by --indent on each item */
  }
</style>

// app/src/components/OutlineItem.tsx
import React, { memo, useRef, useEffect, useCallback, useState } from 'react';
import { Editor } from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import type { TreeNode } from '../lib/types';
import { useOutlineStore } from '../store/outlineStore';

interface OutlineItemProps {
  item: TreeNode;
  onNavigateToNode?: (nodeId: string) => void;
  isInFocusedSubtree?: boolean;
}

// Memoized to prevent unnecessary re-renders
export const OutlineItem = memo(function OutlineItem({
  item,
  onNavigateToNode,
  isInFocusedSubtree = false
}: OutlineItemProps) {
  const { node, depth, hasChildren, children } = item;

  // Store selectors - use individual selectors for better performance
  const focusedId = useOutlineStore(state => state.focusedId);
  const setFocusedId = useOutlineStore(state => state.setFocusedId);
  const addSiblingAfter = useOutlineStore(state => state.addSiblingAfter);
  const updateContent = useOutlineStore(state => state.updateContent);
  const deleteNode = useOutlineStore(state => state.deleteNode);
  const toggleCollapse = useOutlineStore(state => state.toggleCollapse);
  const toggleCheckbox = useOutlineStore(state => state.toggleCheckbox);
  const toggleNodeType = useOutlineStore(state => state.toggleNodeType);
  const indentNode = useOutlineStore(state => state.indentNode);
  const outdentNode = useOutlineStore(state => state.outdentNode);
  const swapWithPrevious = useOutlineStore(state => state.swapWithPrevious);
  const swapWithNext = useOutlineStore(state => state.swapWithNext);
  const moveToPrevious = useOutlineStore(state => state.moveToPrevious);
  const moveToNext = useOutlineStore(state => state.moveToNext);
  const moveToFirst = useOutlineStore(state => state.moveToFirst);
  const moveToLast = useOutlineStore(state => state.moveToLast);

  const isFocused = focusedId === node.id;
  const editorContainerRef = useRef<HTMLDivElement>(null);
  const editorRef = useRef<Editor | null>(null);
  const [editorReady, setEditorReady] = useState(false);

  // Keep stable refs to store functions to avoid stale closures in editor
  const storeRef = useRef({
    addSiblingAfter,
    deleteNode,
    updateContent,
    toggleCollapse,
    toggleCheckbox,
    toggleNodeType,
    indentNode,
    outdentNode,
    swapWithPrevious,
    swapWithNext,
    moveToPrevious,
    moveToNext,
    moveToFirst,
    moveToLast,
    setFocusedId,
  });

  // Update refs when functions change
  useEffect(() => {
    storeRef.current = {
      addSiblingAfter,
      deleteNode,
      updateContent,
      toggleCollapse,
      toggleCheckbox,
      toggleNodeType,
      indentNode,
      outdentNode,
      swapWithPrevious,
      swapWithNext,
      moveToPrevious,
      moveToNext,
      moveToFirst,
      moveToLast,
      setFocusedId,
    };
  });

  // Create or destroy editor based on focus state
  useEffect(() => {
    if (isFocused && editorContainerRef.current && !editorRef.current) {
      const nodeId = node.id;

      // Create editor when focused
      const editor = new Editor({
        element: editorContainerRef.current,
        extensions: [
          StarterKit.configure({
            heading: false,
            bulletList: false,
            orderedList: false,
            blockquote: false,
            codeBlock: false,
            horizontalRule: false,
            hardBreak: false,
          }),
        ],
        content: node.content || '',
        editorProps: {
          attributes: {
            class: 'outline-editor',
          },
          handleKeyDown: (view, event) => {
            const mod = event.ctrlKey || event.metaKey;
            const store = storeRef.current;

            // === TAB HANDLING ===
            if (event.key === 'Tab') {
              event.preventDefault();
              event.stopPropagation();
              if (event.shiftKey) {
                store.outdentNode(nodeId);
              } else {
                store.indentNode(nodeId);
              }
              return true;
            }

            // === EDITING ===
            if (event.key === 'Enter' && !mod && !event.shiftKey) {
              event.preventDefault();
              store.addSiblingAfter(nodeId);
              return true;
            }

            if (event.key === 'Backspace' && mod && event.shiftKey) {
              event.preventDefault();
              store.deleteNode(nodeId);
              return true;
            }

            if (event.key === 'Backspace' && !mod && !event.shiftKey) {
              const { from } = view.state.selection;
              const isEmpty = view.state.doc.textContent.length === 0;
              if (from === 1 && isEmpty) {
                event.preventDefault();
                store.deleteNode(nodeId);
                return true;
              }
            }

            if (event.key === 'Delete' && !mod && !event.shiftKey) {
              const isEmpty = view.state.doc.textContent.length === 0;
              if (isEmpty) {
                event.preventDefault();
                store.deleteNode(nodeId);
                return true;
              }
            }

            // === NAVIGATION ===
            if (event.key === 'ArrowUp' && !mod && !event.shiftKey) {
              event.preventDefault();
              store.moveToPrevious();
              return true;
            }

            if (event.key === 'ArrowDown' && !mod && !event.shiftKey) {
              event.preventDefault();
              store.moveToNext();
              return true;
            }

            if (event.key === 'ArrowUp' && (event.shiftKey || mod)) {
              event.preventDefault();
              store.swapWithPrevious(nodeId);
              return true;
            }

            if (event.key === 'ArrowDown' && (event.shiftKey || mod)) {
              event.preventDefault();
              store.swapWithNext(nodeId);
              return true;
            }

            if (event.key === 'Home' && mod) {
              event.preventDefault();
              store.moveToFirst();
              return true;
            }

            if (event.key === 'End' && mod) {
              event.preventDefault();
              store.moveToLast();
              return true;
            }

            // === COLLAPSE/EXPAND ===
            if (event.key === '.' && mod) {
              event.preventDefault();
              store.toggleCollapse(nodeId);
              return true;
            }

            // === COMPLETION ===
            if (event.key === 'Enter' && mod && !event.shiftKey) {
              event.preventDefault();
              store.toggleCheckbox(nodeId);
              return true;
            }

            if (event.key.toLowerCase() === 'x' && mod && event.shiftKey) {
              event.preventDefault();
              store.toggleNodeType(nodeId);
              return true;
            }

            return false;
          },
        },
        onUpdate: ({ editor }) => {
          storeRef.current.updateContent(nodeId, editor.getHTML());
        },
        onFocus: () => {
          storeRef.current.setFocusedId(nodeId);
        },
      });

      editorRef.current = editor;
      setEditorReady(true);

      // Focus the editor
      setTimeout(() => {
        editor.commands.focus('end');
      }, 0);
    } else if (!isFocused && editorRef.current) {
      // Destroy editor when losing focus
      editorRef.current.destroy();
      editorRef.current = null;
      setEditorReady(false);
    }

    return () => {
      if (editorRef.current) {
        editorRef.current.destroy();
        editorRef.current = null;
      }
    };
  }, [isFocused, node.id, node.content]);

  // Sync content from store to editor when it changes externally
  useEffect(() => {
    const editor = editorRef.current;
    if (editor && !editor.isFocused) {
      const currentContent = editor.getHTML();
      if (currentContent !== node.content) {
        editor.commands.setContent(node.content || '');
      }
    }
  }, [node.content]);

  const handleCollapseClick = useCallback(() => {
    toggleCollapse(node.id);
  }, [node.id, toggleCollapse]);

  const handleBulletDblClick = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setFocusedId(node.id);
  }, [node.id, setFocusedId]);

  const handleCheckboxClick = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    toggleCheckbox(node.id);
  }, [node.id, toggleCheckbox]);

  const handleRowClick = useCallback((e: React.MouseEvent) => {
    const target = e.target as HTMLElement;
    if (target.closest('.outline-editor') || target.closest('.drag-handle')) {
      return;
    }
    setFocusedId(node.id);
  }, [node.id, setFocusedId]);

  const handleStaticClick = useCallback(() => {
    setFocusedId(node.id);
  }, [node.id, setFocusedId]);

  // Strip HTML tags for static display
  const staticContent = node.content?.replace(/<[^>]*>/g, '') || '\u00A0';

  return (
    <div
      className={`outline-item ${isFocused ? 'focused' : ''} ${node.is_checked ? 'checked' : ''}`}
      style={{ marginLeft: depth * 24 }}
    >
      <div className="item-row" onClick={handleRowClick}>
        {/* Drag handle / bullet / checkbox */}
        <span className="drag-handle">
          {node.node_type === 'checkbox' ? (
            <button
              className={`checkbox-btn ${node.is_checked ? 'checked' : ''}`}
              onClick={handleCheckboxClick}
              tabIndex={-1}
              aria-label={node.is_checked ? 'Mark incomplete' : 'Mark complete'}
            >
              <span className={`checkbox-icon ${node.is_checked ? 'checked' : ''}`}>
                {node.is_checked ? '✓' : ''}
              </span>
            </button>
          ) : (
            <span
              className={`bullet ${hasChildren ? 'has-children' : ''} ${node.collapsed ? 'collapsed' : ''}`}
              onClick={hasChildren ? handleCollapseClick : undefined}
              onDoubleClick={handleBulletDblClick}
            >
              {hasChildren && node.collapsed ? '◉' : '●'}
            </span>
          )}
        </span>

        {/* Editor or static content */}
        <div className="editor-wrapper">
          {isFocused ? (
            <div ref={editorContainerRef} className="editor-container"></div>
          ) : (
            <div className="static-content" onClick={handleStaticClick}>
              <p>{staticContent}</p>
            </div>
          )}
        </div>
      </div>

      {/* Recursive children */}
      {hasChildren && !node.collapsed && (
        <div className="children-wrapper">
          <div className="indent-guide"></div>
          <div className="children">
            {children.map(child => (
              <OutlineItem
                key={child.node.id}
                item={child}
                onNavigateToNode={onNavigateToNode}
                isInFocusedSubtree={isFocused || isInFocusedSubtree}
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
});

export default OutlineItem;
